[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  # Disable secrets scanning for Firebase keys
  SECRETS_SCAN_SMART_DETECTION_ENABLED = "false"
  SECRETS_SCAN_SMART_DETECTION_OMIT_VALUES = "true"

# Ignore Firebase configuration files from secrets scanning
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Redirect rules
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
